.TH MAN2PDF 1 "January 13, 2014"
.SH "NAME"
man2pdf \- exports man pages to Preview.app to save as PDF
.SH "SYNOPSIS"
.B man2pdf
[
.BI manpage
]
[
.BI \-h
]
[
.BI \-i
]

.SH "DESCRIPTION"
.I man2pdf
is a command-line utility that will open Unix man pages in Preview.app. The syntax is the same as the man(1) utility.
.PP
.I man2pdf
will read a manpage using grep(1) and then pass it to
.I Preview
for a specified manpage. Any subsequent manpages are ignored. If no man page is specified, the
.I help
page will be displayed.
.PP
.SH USAGE
.I manpage
\- specifies which manpage requested to be parsed to Preview
.PP
.I \-h
\- flag opens the
.I help
menu
.PP
.I \-i
\- installs this manpage for OS X
.PP
To display the man page for
.I echo
would require echo to be specified after the man2pdf call:
.PP
.I man2pdf echo
.SH "SEE ALSO"
.PP
Preview, man(1), whereis(1)
.SH AUTHOR
.PP
Danijel James <danijel.james@gmail.com>
.PP
Please send any bug reports/suggestions.

